### ISSUE TITLE
ELF: not found

### ISSUE THREAD

**Issue by Shatur** [JohnnyMorganz/stylua-action#39]
This action became broken today with a strange error. Here is an example run I did on my configuration:
https://github.com/Shatur/neovim-config/actions/runs/3100298861/jobs/5020418947
I have the same error on my plugins.

**Comment by JohnnyMorganz** [comment]
Ah it is because we introduced linux-aarch64 binaries but the action runner doesn't pick the correct one.
Sorry! I'll get that fixed

**Comment by JohnnyMorganz** [comment]
Fixed in https://github.com/JohnnyMorganz/stylua-action/commit/493d4c8195dd6554e64516792fadea94ae370d62 and released v1.1.1
