### ISSUE TITLE
Please provide a git tag that points to the latest stable version

### ISSUE THREAD

**Issue by dundargoc** [JohnnyMorganz/stylua-action#40]
It's possible to choose the latest commit by just specifying the main branch, but it'd be nice to have a way to point to the latest stable version. The official github actions does this by manually moving their `v1`, `v2`, `v3`... tags to point to the latest stable versions ([example](https://github.com/actions/checkout/tags)). Another common way to do this is to use the git tag `latest` if one doesn't want to mess with multiple versions.

Somewhat related: the @v1 in the README example doesn't work because there is no git tag "v1".

**Comment by JohnnyMorganz** [comment]
Thanks for pointing this out, it has been added https://github.com/JohnnyMorganz/stylua-action/releases/tag/v1
