### ISSUE TITLE
"Could not find asset for v0.14.3 on platform linux" when trying to use a version

### ISSUE THREAD

**Issue by dundargoc** [JohnnyMorganz/stylua-action#41]
When trying to pin to a stylua version `0.14.3` I get the error `Could not find asset for v0.14.3 on platform linux`. I've tried it with and without strings, and I've also tried using `v0.14.3` to no avail.

[CI logs](https://github.com/neovim/neovim/actions/runs/3106103457/jobs/5032559131)

**Comment by JohnnyMorganz** [comment]
Apologies, I seem to have made a mess of the new artifact names. v1.1.1 will try to check for `-x86_64` on the end, which is not present in artifacts < 0.15.0
This should work in v1.1.0. Will fix it for `v1` in general

**Comment by JohnnyMorganz** [comment]
Fixed in https://github.com/JohnnyMorganz/stylua-action/commit/b01f0cf174adf7b3891599fa03ef1a0f48aac8a7 and released in `v1.1.2` and `v1`
