### ISSUE TITLE
[Request] allow disabling the warning about pinning the version

### ISSUE THREAD

**Issue by dundargoc** [JohnnyMorganz/stylua-action#44]
Currently we get the following warning when using stylua-action:

> No version provided, or version provided is malformed, using latest release version. We recommend pinning the version explicitly to handle changes in formatting.

I assumed that this warning would go away when we explicitly pinned the version to `latest`, but that didn't seem to work. Is this intended behaviour? If so, is there another way to disable the warning? We have considered the warning and have come to the conclusion that using the latest version is a risk we're willing to take, even if pinning the version is safer.

**Comment by JohnnyMorganz** [comment]
If its been explicitly set as `latest`, yeah it should not error, seems like a bug. Its mainly there so people understand what happens when no version is provided at all
