### ISSUE TITLE
Can be used to just install stylua?

### ISSUE THREAD

**Issue by danielo515** [JohnnyMorganz/stylua-action#46]
Hello, thanks for this extension.

I am in a situation where I need to install stylua so my test scripts can run it, but I don't want to run anything outside of it. Is it possible for this action to just install stylua without executing anything and just make stylua bin available?

**Comment by JohnnyMorganz** [comment]
I'm not too sure. You could try just setting the args to `-v` so it prints out the version and does nothing else, and then the executable should be available to use.

Alternatively you might be interested in using something like aftman or foreman https://github.com/LPGhatguy/aftman

**Comment by danielo515** [comment]
> Alternatively you might be interested in using something like aftman or foreman https://github.com/LPGhatguy/aftman

Will those work on GitHub actions?
In any case, nevermind. I just forked this action and modified it to suit my needs. God bless open source and you.
Thanks, you can close the issue.
