### ISSUE TITLE
[Features] Allow running with --features lua52

### ISSUE THREAD

**Issue by SuperBo** [JohnnyMorganz/stylua-action#54]
Hi @JohnnyMorganz, My code is currently use label feature of lua, however it is not enabled by default in release version.

Are there anyway for me to enable features like `lua52` when running this action?

Thank you for your great Stylua and this github action.

**Comment by JohnnyMorganz** [comment]
The release version does have lua52 enabled.
What kind of error are you seeing?

You may be experiencing an issue similar to #402 where Luau syntax clashes with Lua 5.2 syntax. You can use cargo to build a binary with only lua52 enabled and that should work. Hopefully in the next major release we will have runtime configurable syntax selection

**Comment by SuperBo** [comment]
@JohnnyMorganz, sorry for not mentioning the error. I met this https://github.com/JohnnyMorganz/StyLua/issues/407.

I managed to use cargo-instal action to install stylua instea.

**Comment by JohnnyMorganz** [comment]
StyLua v2.0.0 now provides support for runtime syntax selection. You can configure this in either in the `stylua.toml` file, or on the command line with `--syntax lua52`.

**Comment by SuperBo** [comment]
thank you for this feature @JohnnyMorganz <3
