### ISSUE TITLE
Inheriting custom shell/environment settings when running format checks (e.g., MINGW/MSYS2)

### ISSUE THREAD

**Issue by rdw-software** [JohnnyMorganz/stylua-action#55]
Hello! This may be a simple configuration issue or not a supported use case, but maybe you have an idea.

I've been using this action to verify the formatting on Windows, macOS, and Linux runners. My setup unfortunately requires MSYS2 (MINGW64) on Windows, which necessitates running all commands in the shell defined via a dedicated setup block, like this:

```yml
    defaults:
      run:
        shell: msys2 {0}
 ```
 
However, while debugging some (possibly unrelated) failures I noticed that the `stylua` command always runs in `pwsh`:

```sh
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { } ; try { [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\3355e2f5-a019-4d80-8578-49a4fe2a279b', 'D:\a\_temp\6d567320-a7ce-4a69-a125-82cc092419a1', $true) } catch { if (($_.Exception.GetType().FullName -eq 'System.Management.Automation.MethodException') -or ($_.Exception.GetType().FullName -eq 'System.Management.Automation.RuntimeException') ){ Expand-Archive -LiteralPath 'D:\a\_temp\3355e2f5-a019-4d80-8578-49a4fe2a279b' -DestinationPath 'D:\a\_temp\6d567320-a7ce-4a69-a125-82cc092419a1' -Force } else { throw $_ } } ;"
D:\a\_temp\6d567320-a7ce-4a69-a125-82cc092419a1\stylua.exe --check . --verbose
```

Is there a way to change the environment for this action? I couldn't find anything in the repository, nor in the GHA docs.

The problem only affects CI runs with MSYS2/Windows, which makes it difficult to debug. Workarounds like installing `stylua` manually, or building with the MSYS version of `cargo` would be more complicated and/or slower, though. Thank you for your time!

**Comment by JohnnyMorganz** [comment]
We just end up calling out to "actions/exec": https://github.com/JohnnyMorganz/stylua-action/blob/b6661824b86c9c33121bed87a778b660ba90cf77/src/main.ts#L59

Looking at its implementation there might be an environment variable "COMSPEC" that you can override: https://github.com/actions/toolkit/blob/main/packages/exec/src/toolrunner.ts#L113. But it defaults to cmd.exe not pwsh so maybe this isn't correct.

I'm not too familiar with the internals but maybe you can find something relevant from this

**Comment by rdw-software** [comment]
Unfortunately, `COMSPEC` only controls [how batch files are processed](https://github.com/actions/toolkit/blob/29d342f1765379a4ab7b028e4c683928f23030a9/packages/exec/src/toolrunner.ts#L143-L149). In this case, `toolPath` should be `stylua.exe` so it wouldn't be affected by this setting. Based on [GitHub's docs](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsstepsrun), it might be possible to use a different `shell`for composite actions. Given the added complexity, I don't know if this kind of flexibility is something you'd want to support?

I could experiment in a fork and see if I can get it to work, but `using: 'node20'` is almost certainly easier. For now, I've opted to simply download the release via `wget` and export the `PATH` manually from within the MSYS2 environment.

**Comment by rdw-software** [comment]
I've found a solution that doesn't require using MSYS2 for this particular problem.
